export interface Usuario {
  email ?:string,
  nome  ?:string,
  senha ?:string,
  cnpj  ?:string,
  telef ?:string,
  lougra?:string,
  numero?:string,
  compl ?:string,
  cidade?:string,
  bairro?:string,
  cep   ?:string,
  estado?:string,
  data  ?:string,
  auth  ?:boolean,
  token ?:string,
}
